
#define METADATA_DATATYPE "datatype"
#define METADATA_NUMBER_OF_ROWS "number_of_rows"

#define TYPE_POINT 1
#define TYPE_RECTANGLE 2
#define TYPE_POINTPOINT 3
#define TYPE_POINTRECTANGLE 4
#define TYPE_RECTANGLERECTANGLE 5

#define COLLECTION_STRUCT_UNSORTED 10
#define COLLECTION_STRUCT_SORTEDX 11
#define COLLECTION_STRUCT_SORTEDY 12
#define COLLECTION_STRUCT_HILBERT 13
